---

- name: Deploy Renku prerequisities
  k8s:
    state: present
    definition: "{{ lookup('template', item + '.yaml.j2')}}"
  with_items:
    - tiller
    - acme
  when: renku_spec[item]

- name: change host in the value files for helm
  shell: sed "s;#@renku@#;$HOST;g" values-template.yaml > values.yaml

- name: render the helm charts
  shell: helm template renku --namespace ${RENKU_NAMESPACE} -f values.yaml renku-${RENKU_VERSION}.tgz > renku.yaml


- name: Deploy Renku
  k8s:
    state: present
    definition: "{{ lookup('file', renku.yaml') }}"