apiVersion: v1
data:
  htpasswd: cmVua3U6JDJ5JDA1JDlCSUc4blprUXJBTmpKM2FiWnNpeE90R3hKM0RrbmZPSGNqN2llUW45UGZqZC4yRW15WWcyCnBhbWVsYTokMnkkMDUkSzg0dkdUbTMyOTlyQlI5TTBOTDd6TzRETDFGRkMyMnNuVU1wTEg1N25mbDJ2R3NkUFNFYi4KYW5kcmVhczokMnkkMDUkZ1RSZE15Szc0VjVBQzZVaUNXLkt6LnMwRFZVMER0SnVPalhGQlhPMFdUSm9Ha1oxTXh3T3EKZm90aXM6JDJ5JDA1JEpvaE5OWmVrb3kxamk2ME9RL2ZMRi4zdy5mMjlwck54Ni5Jb2pETXQvSk1VZTUwcFRYMkhHCnJvazokMnkkMDUkaUN6TnRMakN0SnEweXl3RzF2MC5UT0hlTGJsVURuVzFzcWpPYnBaSVpUUnEuNUVWQW81bi4KZGV2ZWxvcGVyOiQyeSQwNSRuQlNyT2doc3JvZnBxL0lEU05aNS5lVkdveHcxdThhNVNKYUl0bVMyazY5NDREdTI5VUNJYQpqa3JlbXNlcjokMnkkMDUkaWhZVmtyYWlXN1FCdUFFZFVlQUVEZVdscVNCRmw3TGV4WVRoai9iZG9rS1U2RS5xdXNjRmEK
kind: Secret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
