apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: renkus.renku.io
spec:
  group: renku.io
  names:
    kind: Renku
    listKind: RenkuList
    plural: renkus
    singular: renku
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
